pipeline {
    agent { label 'Dev' }
    tools {
        maven 'maven3'  
        jdk 'jdk17'              
    }
    environment {
        SCANNER_HOME = tool name: 'sonar-scanner'
    }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/s7testar/Dev.git'
            }
        }
        stage('Compile') {
            steps {
                dir('Fullstackblockingapp') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('Fullstackblockingapp') {
                    sh 'mvn test'
                }
            }
        }
        stage('Trivy FS Scan') {
            steps {
                dir('Fullstackblockingapp') {
                    sh 'trivy fs --format table -o fs.html .'
                }
            }
        }
        stage('Sonar Analysis') {
            steps {
                dir('Fullstackblockingapp') {
                    withSonarQubeEnv('sonar') {
                        sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectKey=Logging-app -Dsonar.projectName=Logging-all -Dsonar.java.binaries=target -Dsonar.host.url=http://192.168.56.11:9000'''
                    }
                }
            }
        }
        stage('Publish Artifacts') {
            agent { label "docker" }
            steps {
                dir('Fullstackblockingapp') {
                    withMaven(globalMavenSettingsConfig: 'settings-maven', maven: 'maven3', jdk: 'jdk17', mavenSettingsConfig:'',traceability:true) {
                        sh 'mvn deploy'
                    }
                }
            }
        }
        stage('Docker Build & Tag') {
            agent { label 'docker' }
            steps {
                dir('Fullstackblockingapp') {
                script{
                    withDockerRegistry(credentialsId: 'docker-login', toolName: 'docker') {
                        sh 'docker build -t attamegnon/prod:${JOB_NAME}_v${BUILD_NUMBER} -f Dockerfile .'
                       }
                    }
                }
            }
        }
        stage('Trivy Image Scan') {
            agent { label 'docker' }
            steps {
                sh 'trivy image --format table -o image.html attamegnon/prod:${JOB_NAME}_v${BUILD_NUMBER}'
            }
        }
        stage('Docker Push Images') {
            agent { label 'docker' }
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-login', toolName: 'docker') {
                        sh 'docker push attamegnon/prod:${JOB_NAME}_v${BUILD_NUMBER}'
                    }
                }
            }
        }
        stage('K8s Deploy') {
            agent { label 'docker' }
            steps {
                dir('Fullstackblockingapp') {
                    withKubeConfig(caCertificate: '', clusterName: 'master-node', contextName: '', credentialsId: 'projectstack', namespace: 'stack', restrictKubeConfigAccess: false, serverUrl: 'https://192.168.56.11:6443') {
                        sh "kubectl apply -f deployment-service.yml"
                        sleep 30 // Consider replacing this with a readiness check
                    }
                }
            }
        }
        stage('Verify Deployment') {
            agent { label 'docker' }
            steps {
                withKubeConfig(caCertificate: '', clusterName: 'master-node', contextName: '', credentialsId: 'projectstack', namespace: 'stack', restrictKubeConfigAccess: false, serverUrl: 'https://192.168.56.11:6443') {
                    sh "kubectl get pods -n stack"
                    sh "kubectl get svc -n stack"
                }
            }
        }
    }

post {
always {
   script {
       def jobName = env.JOB_NAME
       def buildNumber = env.BUILD_NUMBER
       def pipelineStatus = currentBuild.result ?: 'UNKNOWN'
       def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'
       
       def body = """
           <html>
           <body>
           <div style="border: 4px solid ${bannerColor}; padding: 10px;">
           <h2>${jobName} - Build ${buildNumber}</h2>
           <div style="background-color: ${bannerColor}; padding: 10px;">
           <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
           </div>
           <p>Check the <a href="${BUILD_URL}">console output</a>.</p>
           </div>
           </body>
           </html>
       """
       emailext(
           subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
           body: body,
           to: 'attamegnon@gmail.com',
           from: 'jenkins@example.com',
           replyTo: 'jenkins@example.com',
           mimeType: 'text/html',
           )
        }
      }
        
    }
  }


