apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: maven-deployment
spec:
  selector:
    matchLabels:
      app: maven
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: maven
          image: attamegnon/dev:maven_v21 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8083 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: maven-ssvc
spec:
  selector:
    app: maven
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8083
      nodePort: 30007
  type: NodePort # type of the service.
